CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	sw_allow BOOLEAN NOT NULL CHECK (sw_allow IN (0, 1)),
	creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	audit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);